### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by ApeToe** [LondonStudios/PoliceHandbookFiveM#1]
Something about this seems off, theres not enough information.. a british handbook? What commands? Nothing but a blank DLL doing god knows what?

**Comment by ApeToe** [comment]
Found this after some searching, don't know why its not included in the readme. 

https://forum.cfx.re/t/british-police-handbook-uk-legislation-gowisely-ipp-arrest-more-server-side-script/1156326

**Comment by LondonStudios** [comment]
> Found this after some searching, don't know why its not included in the readme.
> 
> https://forum.cfx.re/t/british-police-handbook-uk-legislation-gowisely-ipp-arrest-more-server-side-script/1156326

Hi,
This was mainly to be linked from, not to be found on Git-Hub but I will add a Read-Me file.

**Comment by ApeToe** [comment]
Yeah sorry, I typically browse here before trying to prove I'm not a bot to fivem for the thousandth time.
